name: nodejs feature pipeline
on: 
  workflow_call:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: string
      component:
        description: 'Component name'
        required: true
        type: string
env:
  project: ${{ inputs.project }}
  component: ${{ inputs.component }}
  acc_id: 220719767845

jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: read packed.json version
        id: package_version
        run: |
          APP_VERSION=$(jq -r .version package.json)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: print the version
        run: echo "$APP_VERSION"

      - name: install dependencies
        run: npm install

      - name: unit test
        id: unit_tests
        run: npm test  